## Append samples of your project ##
resources:
- v1beta1_profile.yaml
- v1beta1_downloader.yaml
- v1beta1_uploader.yaml
- v1beta1_crawler.yaml
- v1beta1_search.yaml
- v1beta1_cronsearch.yaml
- v1beta1_clusterdownloader.yaml
- v1beta1_clustercrawler.yaml
- v1beta1_clusteruploader.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
