resources:
  - ../default

images:
  - name: ghcr.io/crashappsec/ocular-controller
    newTag: e2e-test
    newName: ocular-controller

configMapGenerator:
  - name: controller-manager-config
    behavior: merge
    literals:
      - OCULAR_SIDECAR_IMG=ocular-sidecar:e2e-test